project:
  title: "Rapportage waterkwaliteit 2024 - HHSK"
  type: book
  post-render: 
   - "R/post_render_zwem_icons.R"
book:
  title: "Rapportage waterkwaliteit 2024"
  sidebar:
    title: "Rapportage waterkwaliteit 2024"
  # cover-image: "images/zomer_veenweide_full_colour_800px.jpg"
  # sidebar: 
  #   logo: "images/logo_hhsk.png"
  page-footer: 
    center: 
      "![](images/schonevoeten.png){width=50%}"
  page-navigation: true
  twitter-card: true
  open-graph: true
  # abstract-title: "Introductie"
  # abstract: ""
  search: true
  # author: "Jane Doe"
  date: today
  chapters:
    - "index.qmd"
    - "01-zichtbare-toestand.qmd"
    - "02-krw.qmd"
    - "03-zwemwater.qmd"
    - "04-nutrienten.qmd"
    - "05-bestrijdingsmiddelen.qmd"
    - "06-meetnetten.qmd"
    - "09-meer_info.qmd"
    - "98-colofon.qmd"
format:
  html:
    css: "styles_wklrap.css"
    theme: 
      - cosmo
      - brand
    fig-format: svg
    # cap-location: margin
    reference-location: document
brand: "brand/_brand.yml"
lang: nl
language: 
  nl:
    section-title-abstract: ""
    title-block-published: "Datum"
    toc-title-document: "In dit hoofdstuk"
    crossref-fig-title: "Figuur"
    crossref-tbl-title: "Tabel"
    crossref-ch-prefix: "hoofdstuk"
    
execute: 
  freeze: auto
  echo: false
  warning: false
  message: false
# code-tools: true
# filters:
#    - lightbox
